### ISSUE TITLE
Error detected while processing function <SNR>13_ctags_gen..gen_tags#system_async..<SNR>26_job_start:

### ISSUE THREAD

**Issue by hunanchenxingyu** [jsfaint/gen_tags.vim#40]
> Error detected while processing function <SNR>13_ctags_gen..gen_tags#system_async..<SNR>26_job_start:
> line   30:
> E730: using List as a String
> E484: Can't open file /tmp/vg34F29/1

Does anyone met the problem above when i run the "GenCtags" in vim ？

**Comment by jsfaint** [comment]
Do you upgrade to the latest master? This issue was fixed by commit 7bb947d2a5fee45b3e058adf29d43be0a59262a6 and 39c057253aff63453fdd56e0eb8541a3effb03d4 already

**Comment by hunanchenxingyu** [comment]
Yes，I download it just now, and i am working on the ubuntu-12.04(vim: 7.3.429, Python 2.7.6).

**Comment by hunanchenxingyu** [comment]
@jsfaint Have you any other suggestions ?

**Comment by jsfaint** [comment]
OK. `vim: 7.3.429` is the old version which don't support `jobcontrol`, I'll check it later.

**Comment by hunanchenxingyu** [comment]
Thank you

**Comment by jsfaint** [comment]
I checked the help of vim, use list as input of system() was added in vim 7.4.247.
```
Patch 7.4.247
Problem:    When passing input to system() there is no way to keep NUL and
	    NL characters separate.
Solution:   Optionally use a list for the system() input. (ZyX)
Files:	    runtime/doc/eval.txt, src/eval.c
```

I'll make a patch to fix this issue.

**Comment by hunanchenxingyu** [comment]
Get it, Look forward to your patch.

**Comment by jsfaint** [comment]
@hunanchenxingyu Please check the latest mater branch. thanks

**Comment by hunanchenxingyu** [comment]
Yes, i try it, it looks right when i run the "GenCtags", but can't generate the tags file in [home]/.cache/tags_dir/xxx. There are some errors when i run "ClearCtags!", as follows:

> Error detected while processing function <SNR>12_ctags_clear:
> line   18:
> E118: Too many arguments for function: delete

**Comment by jsfaint** [comment]
> Yes, i try it, it looks right when i run the "GenCtags", but can't generate the tags file in [home]/.cache/tags_dir/xxx. 

It's a typo in source code, I'll fix it.

> There are some errors when i run"ClearCtags!", as follows:
>> Error detected while processing function 12_ctags_clear:
line 18:
E118: Too many arguments for function: delete

That's because vim 7.3.429 don't support parameter for delete(). I'll add a workaround for it.
```
Patch 7.4.1107
Problem:    Vim can create a directory but not delete it.
Solution:   Add an argument to delete() to make it possible to delete a
            directory, also recursively.
Files:      src/fileio.c, src/eval.c, src/proto/fileio.pro,
            src/testdir/test_delete.vim, src/testdir/test_alot.vim,
            runtime/doc/eval.txt
```

BTW: I suggest you upgrade to newer version of vim, if possible. 😄

**Comment by hunanchenxingyu** [comment]
> >  Yes, i try it, it looks right when i run the "GenCtags", but can't generate the tags file in [home]/.cache/tags_dir/xxx.
> 
> It's a typo in source code, I'll fix it.

Ok, I have upgraded the vim to 7.4.692 just now, and it also can't generate the tags.

**Comment by jsfaint** [comment]
@hunanchenxingyu Fixed
I test on vim 7.4.692 which also don't support jobcontrol.
It works now.

**Comment by hunanchenxingyu** [comment]
It will result in the terminal stuck after using the shortcut key "ctrl + ]" to skip.

**Comment by jsfaint** [comment]
> It will result in the terminal stuck after using the shortcut key "ctrl + ]" to skip.

Do you use a huge codebase?
ctags is very slow when the tags file is large.

It's limitation in ctags, It can't be fixed by `gen_tags.vim`

**Comment by hunanchenxingyu** [comment]
@jsfaint the tags file is only 460M, and i found it maybe result in the terminal stuck when generate the tags background.

It will report a warning when i set the parameter as follows:

> let g:gen_tags#ctags_opts = "-I __THROW -file-scope=yes -langmap=c:+.h -languages=c,c++ -links=yes -c-kinds=+p --fields=+S"

**ctags: Warning: -f option specified more than once, last value used^@ctags: Unknown option: -l^@**

Do you have any better suggestions to me ? thanks.

**Comment by hunanchenxingyu** [comment]
I have resolved it, and lack of "-" in g:gen_tags#ctags_opts, as follows:

> let g:gen_tags#ctags_opts = "-I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c-kinds=+p --fields=+S"

The gen_tags is work well at present, thanks for @jsfaint 'help again.
